### ISSUE TITLE
Documenting UI components

### ISSUE THREAD

**Issue by hputzek** [GridSound/gs-ui-components#6]
Hey Thomas

I am working on an led controller for live visuals/light control at the moment.
This is how I came to your repo:
I'm planning my GUI and saw that you built a LOT of great components. <3

I plan to use https://storybook.js.org/ in my  [vue](https://vuejs.org/) app.

Maybe you could benefit from a documentation of your ui components, too?
Think of it similary of what you got if you go to codepen and list all your stuff.
But additionally you have some helping sentences and can document properties etc.

If you're interested we can have a talk and I can try to build that all in a way that I can give that back to you.

Another option would be too keep it all in your repo so that I directly add docs there. But in this case we have to plan how to do that before :-)

Furthermore:
Would you be interested in me transforming some of your components to vue? Or extend them in a way that you can use them as they are or in vue context? Or do you want to keep it "framework-less"?

Interested?

Greetings,
Hendrik

FYI: You can find more info here (attention, website not finished yet): 
https://pixelcrasher.app

**Comment by mr21** [comment]
Hi Hendrik :)

**EDIT**: The "doc" for this repo is that simple page 👉 https://gridsound.github.io/gs-ui-components/

Well, the way how those components works has changed since the begining. I want to change them again to follow the Web Components standard. Like this:
``` javascript
class MyComponent extends HTMLElement { ... }
```

All those component has to be state free before and several huge ones are not ready yet, like the gsuiPianoroll and gsuiPatternroll...

But if Storybook is not only for Vue/React then why not, but the document is not my priority because the code is not intended to be used by others.

Your led project looks fun btw ^^

Thanks a lot for your interest in GridSound :)
